#version: '3.8'
#
#services:
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    container_name: zookeeper-user-micro
#    restart: always
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#
#  kafka:
#    image: confluentinc/cp-kafka:latest
#    container_name: kafka-user-micro
#    restart: always
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: PLAINTEXT://:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#
#  user-service:
#    build: .
#    container_name: user-service
#    restart: always
#    depends_on:
#      - kafka
#    ports:
#      - "8082:8082"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/usermicroservice
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: Baku2018
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      SPRING_APPLICATION_NAME: user-service
#    networks:
#      - app-network
#
#  mysql:
#    image: mysql:8
#    container_name: mysql-user-micro
#    restart: always
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: Baku2018
#      MYSQL_DATABASE: usermicroservice
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    driver: bridge
